### ISSUE TITLE
Cannot run CliXO

### ISSUE THREAD

**Issue by y8qin** [fanzheng10/CliXO-1.0#4]
Hi! I cloned the github repo to my laptop and running `./clixo` gives me the following error:
`bash: ./clixo: cannot execute binary file`

Shall I install some other ways?

Thanks!

**Comment by antonkratz** [comment]
The binary is for ubuntu. I assume your laptop is running on a different OS or different CPU. My advice is to try re-compile it!

**Comment by y8qin** [comment]
Thanks Anton! I tried make and got the following errors:

Consolidate compiler generated dependencies of target CliXO
[ 33%] Linking CXX executable CliXO
duplicate symbol 'calculateClusterWeight(boost::dynamic_bitset<unsigned long, std::__1::allocator<unsigned long> >, nodeDistanceObject&)' in:
    CMakeFiles/CliXO.dir/clixo.cpp.o
    CMakeFiles/CliXO.dir/clustersToDAG.cpp.o
duplicate symbol 'dagConstruct::combineClusters(std::__1::vector<std::__1::pair<std::__1::pair<unsigned long, unsigned long>, double>, std::__1::allocator<std::__1::pair<std::__1::pair<unsigned long, unsigned long>, double> > >&, currentClusterClassBitset&, graph_undirected_bitset&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >&, nodeDistanceObject&)' in:
    CMakeFiles/CliXO.dir/clixo.cpp.o
    CMakeFiles/CliXO.dir/clustersToDAG.cpp.o
duplicate symbol '_main' in:
    CMakeFiles/CliXO.dir/clixo.cpp.o
    CMakeFiles/CliXO.dir/clustersToDAG.cpp.o
duplicate symbol 'dagConstruct::clustersToDAG(std::__1::vector<validClusterBitset, std::__1::allocator<validClusterBitset> >, DAGraph&, unsigned int)' in:
    CMakeFiles/CliXO.dir/clixo.cpp.o
    CMakeFiles/CliXO.dir/clustersToDAG.cpp.o
duplicate symbol '_debug' in:
    CMakeFiles/CliXO.dir/clixo.cpp.o
    CMakeFiles/CliXO.dir/clustersToDAG.cpp.o
duplicate symbol 'dagConstruct::constructDAG(graph_undirected&, DAGraph&, nodeDistanceObject&, double, double, double, double, double, bool)' in:
    CMakeFiles/CliXO.dir/clixo.cpp.o
    CMakeFiles/CliXO.dir/clustersToDAG.cpp.o
duplicate symbol 'dagConstruct::getFuzzyClustersBitsetThreshold(nodeDistanceObject&, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, unsigned int, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, unsigned int> > >&, std::__1::vector<validClusterBitset, std::__1::allocator<validClusterBitset> >&, double, double, double, double, double, bool)' in:
    CMakeFiles/CliXO.dir/clixo.cpp.o
    CMakeFiles/CliXO.dir/clustersToDAG.cpp.o
duplicate symbol 'dagConstruct::addMissingEdges(currentClusterClassBitset&, double, double, graph_undirected_bitset&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >&, nodeDistanceObject&, graph_undirected_bitset&, bool)' in:
    CMakeFiles/CliXO.dir/clixo.cpp.o
    CMakeFiles/CliXO.dir/clustersToDAG.cpp.o
duplicate symbol 'dagConstruct::updateClustersWithEdges(std::__1::vector<std::__1::pair<unsigned int, unsigned int>, std::__1::allocator<std::__1::pair<unsigned int, unsigned int> > >&, currentClusterClassBitset&, graph_undirected_bitset&, nodeDistanceObject&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >&, bool)' in:
    CMakeFiles/CliXO.dir/clixo.cpp.o
    CMakeFiles/CliXO.dir/clustersToDAG.cpp.o
duplicate symbol 'dagConstruct::isClusterAncestor(boost::dynamic_bitset<unsigned long, std::__1::allocator<unsigned long> > const&, boost::dynamic_bitset<unsigned long, std::__1::allocator<unsigned long> > const&, boost::dynamic_bitset<unsigned long, std::__1::allocator<unsigned long> >&)' in:
    CMakeFiles/CliXO.dir/clixo.cpp.o
    CMakeFiles/CliXO.dir/clustersToDAG.cpp.o
duplicate symbol 'compClustersToCombine(std::__1::pair<std::__1::pair<unsigned long, unsigned long>, double> const&, std::__1::pair<std::__1::pair<unsigned long, unsigned long>, double> const&)' in:
    CMakeFiles/CliXO.dir/clixo.cpp.o
    CMakeFiles/CliXO.dir/clustersToDAG.cpp.o
duplicate symbol 'compPairSecondDescending(std::__1::pair<unsigned int, unsigned int> const&, std::__1::pair<unsigned int, unsigned int> const&)' in:
    CMakeFiles/CliXO.dir/clixo.cpp.o
    CMakeFiles/CliXO.dir/clustersToDAG.cpp.o
duplicate symbol 'compPairSecondAscending(std::__1::pair<unsigned int, unsigned int> const&, std::__1::pair<unsigned int, unsigned int> const&)' in:
    CMakeFiles/CliXO.dir/clixo.cpp.o
    CMakeFiles/CliXO.dir/clustersToDAG.cpp.o
duplicate symbol 'compDist(std::__1::pair<std::__1::pair<unsigned int, unsigned int>, double>, std::__1::pair<std::__1::pair<unsigned int, unsigned int>, double>)' in:
    CMakeFiles/CliXO.dir/clixo.cpp.o
    CMakeFiles/CliXO.dir/clustersToDAG.cpp.o
duplicate symbol 'dagConstruct::updateCliques(graph_undirected_bitset&, std::__1::vector<boost::dynamic_bitset<unsigned long, std::__1::allocator<unsigned long> >, std::__1::allocator<boost::dynamic_bitset<unsigned long, std::__1::allocator<unsigned long> > > >&, boost::dynamic_bitset<unsigned long, std::__1::allocator<unsigned long> >, std::__1::vector<unsigned int, std::__1::allocator<unsigned int> >&, std::__1::vector<char, std::__1::allocator<char> >&, unsigned int, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >&)' in:
    CMakeFiles/CliXO.dir/clixo.cpp.o
    CMakeFiles/CliXO.dir/clustersToDAG.cpp.o
duplicate symbol 'dagConstruct::findClustsWithSeed(boost::dynamic_bitset<unsigned long, std::__1::allocator<unsigned long> >, graph_undirected_bitset&, std::__1::vector<boost::dynamic_bitset<unsigned long, std::__1::allocator<unsigned long> >, std::__1::allocator<boost::dynamic_bitset<unsigned long, std::__1::allocator<unsigned long> > > >&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >&)' in:
    CMakeFiles/CliXO.dir/clixo.cpp.o
    CMakeFiles/CliXO.dir/clustersToDAG.cpp.o
duplicate symbol 'printCluster(boost::dynamic_bitset<unsigned long, std::__1::allocator<unsigned long> > const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >&)' in:
    CMakeFiles/CliXO.dir/clixo.cpp.o
    CMakeFiles/CliXO.dir/clustersToDAG.cpp.o
duplicate symbol 'dagConstruct::isMinNodeDegreeMet(unsigned int, unsigned int, currentClusterClassBitset&, graph_undirected_bitset&, double, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >&)' in:
    CMakeFiles/CliXO.dir/clixo.cpp.o
    CMakeFiles/CliXO.dir/clustersToDAG.cpp.o
duplicate symbol 'dagConstruct::isSimilar(unsigned int, unsigned int, currentClusterClassBitset&, graph_undirected_bitset&, double, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >&)' in:
    CMakeFiles/CliXO.dir/clixo.cpp.o
    CMakeFiles/CliXO.dir/clustersToDAG.cpp.o
ld: 19 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [CliXO] Error 1
make[1]: *** [CMakeFiles/CliXO.dir/all] Error 2
make: *** [all] Error 2


Any suggestions?

**Comment by fanzheng10** [comment]
hi @y8qin, the binary was compiled on Linux. If you are trying it on Mac, and `make` gives you
`make: Nothing to be done for 'all'.`, you can use `make -B all` to force a rebuild.

A similar approach can be applied If the binary is compiled on Mac, and then copied to a Linux platform (this does not seem necessary before, I'm not sure if anything changed in macOS).

Let me know if the above approach works and if so I will close the issue.
